-- ============================================================
-- Make Down Trivia Royale seed pack
-- Team-game-night trivia: 1 category + 5 quizzes + questions.
-- Bilingual (EN/AR). Run once:
--   mysql -u <db_user> -p <db_name> < sql/seed_trivia_royale.sql
-- ============================================================

SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO game_categories (parent_id, name_en, name_ar, slug, icon_url, sort_order, is_active)
VALUES (NULL, 'Team Game Night: Trivia Royale', 'ليلة ألعاب الفريق: تريفيا رويال', 'trivia-royale-team-game-night', NULL, 100, 1);
SET @trivia_royale_cat_id = LAST_INSERT_ID();

-- ---------- Quiz: Roblox Rush ----------
INSERT INTO quizzes (category_id, title_en, title_ar, description_en, description_ar, cover_image_url, difficulty, supported_modes, created_by_admin_id, is_active)
VALUES (@trivia_royale_cat_id, 'Roblox Rush', 'روبلوكس راش', 'Neon green Roblox trivia - currency, avatars, popular experiences and dev tools.', 'أسئلة عن روبلوكس بألوان نيون خضراء - العملة، الشخصيات، أشهر التجارب وأدوات التطوير.', NULL, 'easy', 'both', NULL, 1);
SET @quiz1_id = LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What do you call Roblox''s in-game currency?', 'ماذا يُطلق على عملة روبلوكس داخل اللعبة؟', NULL, 'text', 'both', NULL, '["Bucks", "Robux", "Coins", "Gems"]', '["باكس", "روبكس", "عملات", "جواهر"]', 1, 200, 20, 1);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What shape are classic Roblox avatar heads by default?', 'ما هو الشكل الافتراضي الكلاسيكي لرأس شخصية اللاعب في روبلوكس؟', NULL, 'text', 'both', NULL, '["Round", "Block/square", "Triangle", "Star"]', '["دائري", "مكعب/مربع", "مثلث", "نجمة"]', 1, 200, 20, 2);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'Which Roblox game lets you adopt and raise virtual pets?', 'أي لعبة في روبلوكس تتيح لك تبني وتربية حيوانات أليفة افتراضية؟', NULL, 'text', 'both', NULL, '["Adopt Me", "Brookhaven", "Piggy", "Blox Fruits"]', '["Adopt Me", "Brookhaven", "Piggy", "Blox Fruits"]', 0, 200, 20, 3);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What''s the name of Roblox''s big annual awards event for creators?', 'ما اسم حفل الجوائز السنوي الكبير الذي يقيمه روبلوكس لصنّاع المحتوى؟', NULL, 'text', 'both', NULL, '["RobloxCon", "Bloxy Awards", "Roblox Fest", "Dev Con"]', '["RobloxCon", "Bloxy Awards", "Roblox Fest", "Dev Con"]', 1, 200, 20, 4);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What does Roblox officially call a game/place made by users?', 'ماذا يسمي روبلوكس رسميًا اللعبة أو المكان الذي يصنعه المستخدمون؟', NULL, 'text', 'both', NULL, '["Level", "World", "Experience", "Zone"]', '["مستوى", "عالم", "تجربة", "منطقة"]', 2, 200, 20, 5);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What coding language do Roblox developers use to build games?', 'ما لغة البرمجة التي يستخدمها مطورو روبلوكس لبناء الألعاب؟', NULL, 'text', 'both', NULL, '["Python", "Lua (Luau)", "JavaScript", "C++"]', '["Python", "Lua (Luau)", "JavaScript", "C++"]', 1, 400, 20, 6);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'In Roblox slang, what''s a "noob"?', 'في مصطلحات روبلوكس، ماذا تعني كلمة "noob"؟', NULL, 'text', 'both', NULL, '["A pro player", "A new/inexperienced player", "A moderator", "A glitch"]', '["لاعب محترف", "لاعب جديد وعديم الخبرة", "مشرف", "خلل تقني"]', 1, 400, 20, 7);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'In "Piggy," what are you running from?', 'في لعبة "Piggy"، ممن تهرب؟', NULL, 'text', 'both', NULL, '["A zombie", "A giant pig villain", "A ghost", "A robot"]', '["زومبي", "خنزير شرير عملاق", "شبح", "روبوت"]', 1, 400, 20, 8);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What do you earn for completing in-game challenges in many Roblox experiences?', 'ماذا تكسب عند إتمام التحديات داخل العديد من تجارب روبلوكس؟', NULL, 'text', 'both', NULL, '["XP", "Badges", "Robux automatically", "Followers"]', '["نقاط خبرة", "شارات", "روبكس تلقائيًا", "متابعين"]', 1, 400, 20, 9);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What''s the free software Roblox developers use to build and design games?', 'ما البرنامج المجاني الذي يستخدمه مطورو روبلوكس لبناء وتصميم الألعاب؟', NULL, 'text', 'both', NULL, '["Roblox Studio", "Roblox Maker", "Roblox Creator", "Roblox Builder"]', '["Roblox Studio", "Roblox Maker", "Roblox Creator", "Roblox Builder"]', 0, 400, 20, 10);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'In "Tower of Hell," what''s the main goal?', 'في لعبة "Tower of Hell"، ما الهدف الرئيسي؟', NULL, 'text', 'both', NULL, '["Build the tallest tower", "Climb to the top before time runs out", "Destroy other towers", "Collect coins"]', '["بناء أطول برج", "التسلق إلى القمة قبل انتهاء الوقت", "تدمير الأبراج الأخرى", "جمع العملات"]', 1, 600, 20, 11);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'Which Roblox game is themed around royal/princess high school role-play?', 'أي لعبة روبلوكس تدور حول تقمص أدوار مدرسة ثانوية ملكية للأميرات؟', NULL, 'text', 'both', NULL, '["Royale High", "Brookhaven", "MeepCity", "Bloxburg"]', '["Royale High", "Brookhaven", "MeepCity", "Bloxburg"]', 0, 600, 20, 12);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'Which Roblox game is about working jobs and living a simulated town life?', 'أي لعبة روبلوكس تتمحور حول العمل وعيش حياة بلدة محاكاة؟', NULL, 'text', 'both', NULL, '["Welcome to Bloxburg", "Adopt Me", "Piggy", "Arsenal"]', '["Welcome to Bloxburg", "Adopt Me", "Piggy", "Arsenal"]', 0, 600, 20, 13);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What type of game is "Arsenal" in Roblox?', 'ما نوع لعبة "Arsenal" في روبلوكس؟', NULL, 'text', 'both', NULL, '["Racing", "First-person shooter", "Simulator", "Obstacle course"]', '["سباق", "إطلاق نار من منظور الشخص الأول", "محاكاة", "مسار عقبات"]', 1, 600, 20, 14);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz1_id, 'What does "obby" mean in Roblox slang?', 'ماذا تعني كلمة "obby" في مصطلحات روبلوكس؟', NULL, 'text', 'both', NULL, '["Obstacle course", "Object builder", "Online battle", "Open bounty"]', '["مسار عقبات", "بناء أجسام", "معركة عبر الإنترنت", "مكافأة مفتوحة"]', 0, 600, 20, 15);

-- ---------- Quiz: Makedown History ----------
INSERT INTO quizzes (category_id, title_en, title_ar, description_en, description_ar, cover_image_url, difficulty, supported_modes, created_by_admin_id, is_active)
VALUES (@trivia_royale_cat_id, 'Makedown History', 'تاريخ ميك داون', 'How well does your team know Make Down? First 6 questions are ready to play - the rest are on the way.', 'إلى أي مدى يعرف فريقك ميك داون؟ الأسئلة الست الأولى جاهزة للعب - والباقي في الطريق.', NULL, 'easy', 'both', NULL, 0);
SET @quiz2_id = LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz2_id, 'Who is the CEO of Makedown?', 'من هو الرئيس التنفيذي لشركة ميك داون؟', NULL, 'text', 'both', NULL, '["Abdullah", "Ali", "Mustafa", "Sabeer"]', '["عبدالله", "علي", "مصطفى", "صابر"]', 1, 200, 20, 1);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz2_id, 'Who is Makedown''s COO?', 'من هو مدير العمليات في ميك داون؟', NULL, 'text', 'both', NULL, '["Rawan Al Saraf", "Abdullah Al Fuzae", "Mustafa", "Sabeer"]', '["روان الصراف", "عبدالله الفزيع", "مصطفى", "صابر"]', 1, 200, 20, 2);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz2_id, 'Who handles Photography for Makedown?', 'من يتولى التصوير الفوتوغرافي في ميك داون؟', NULL, 'text', 'both', NULL, '["Rawan Al Saraf", "Mustafa", "Abdullah", "Sabeer"]', '["روان الصراف", "مصطفى", "عبدالله", "صابر"]', 0, 400, 20, 3);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz2_id, 'Who runs Digital Marketing at Makedown?', 'من يدير التسويق الرقمي في ميك داون؟', NULL, 'text', 'both', NULL, '["Sabeer", "Mustafa", "Rawan", "Abdullah"]', '["صابر", "مصطفى", "روان", "عبدالله"]', 1, 400, 20, 4);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz2_id, 'Who''s the Driver on the Makedown team?', 'من هو السائق في فريق ميك داون؟', NULL, 'text', 'both', NULL, '["Sabeer", "Ali", "Abdullah", "Mustafa"]', '["صابر", "علي", "عبدالله", "مصطفى"]', 0, 600, 20, 5);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz2_id, 'How many people are on the core Makedown team (that we know of)?', 'كم عدد الأشخاص في فريق ميك داون الأساسي (على حد علمنا)؟', NULL, 'text', 'both', NULL, '["3", "5", "7", "10"]', '["3", "5", "7", "10"]', 1, 600, 20, 6);

-- ---------- Quiz: Fortnite Frenzy ----------
INSERT INTO quizzes (category_id, title_en, title_ar, description_en, description_ar, cover_image_url, difficulty, supported_modes, created_by_admin_id, is_active)
VALUES (@trivia_royale_cat_id, 'Fortnite Frenzy', 'فورتنايت فرينزي', 'Purple and electric-blue Fortnite trivia - the Battle Bus, building, seasons and more.', 'أسئلة فورتنايت بألوان بنفسجية وزرقاء كهربائية - الحافلة القتالية، البناء، المواسم والمزيد.', NULL, 'easy', 'both', NULL, 1);
SET @quiz3_id = LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What''s the flying bus that drops players onto the map called?', 'ما اسم الحافلة الطائرة التي تُنزل اللاعبين على الخريطة؟', NULL, 'text', 'both', NULL, '["Battle Bus", "Drop Ship", "Sky Van", "Loot Chopper"]', '["Battle Bus", "Drop Ship", "Sky Van", "Loot Chopper"]', 0, 200, 20, 1);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What currency do players use to buy skins in the Item Shop?', 'ما العملة التي يستخدمها اللاعبون لشراء الأزياء في متجر العناصر؟', NULL, 'text', 'both', NULL, '["Robux", "V-Bucks", "Coins", "Gems"]', '["روبكس", "في-باكس", "عملات", "جواهر"]', 1, 200, 20, 2);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What''s the goal of a standard Battle Royale match?', 'ما هدف مباراة باتل رويال العادية؟', NULL, 'text', 'both', NULL, '["Score the most goals", "Be the last player/team standing", "Collect all gems", "Build the tallest tower"]', '["تسجيل أكبر عدد من الأهداف", "أن تكون آخر لاعب أو فريق باقٍ", "جمع كل الجواهر", "بناء أطول برج"]', 1, 200, 20, 3);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'Which of these is NOT a material you gather to build structures?', 'أي مما يلي ليست مادة تجمعها لبناء الهياكل؟', NULL, 'text', 'both', NULL, '["Wood", "Brick/Stone", "Metal", "Water"]', '["خشب", "طوب/حجر", "معدن", "ماء"]', 3, 200, 20, 4);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What''s the name of the shrinking danger zone in every match?', 'ما اسم منطقة الخطر المتقلصة في كل مباراة؟', NULL, 'text', 'both', NULL, '["The Fog", "The Storm", "The Blackout", "The Void"]', '["الضباب", "العاصفة", "الانقطاع", "الفراغ"]', 1, 200, 20, 5);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'Floss, Take the L, and Orange Justice are all examples of what?', 'Floss وTake the L وOrange Justice كلها أمثلة على ماذا؟', NULL, 'text', 'both', NULL, '["Fortnite dance emotes", "Building materials", "Weapon types", "Game modes"]', '["رقصات تعبيرية في فورتنايت", "مواد بناء", "أنواع أسلحة", "أنماط لعب"]', 0, 400, 20, 6);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What company created Fortnite?', 'أي شركة أنشأت لعبة فورتنايت؟', NULL, 'text', 'both', NULL, '["Activision", "Epic Games", "EA", "Ubisoft"]', '["Activision", "Epic Games", "EA", "Ubisoft"]', 1, 400, 20, 7);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What do you call teaming up with friends in groups of 2, 3, or 4?', 'ماذا يُطلق على تشكيل فريق مع الأصدقاء بمجموعات من 2 أو 3 أو 4؟', NULL, 'text', 'both', NULL, '["Duos/Trios/Squads", "Party mode", "Crew", "Alliance"]', '["ثنائي/ثلاثي/رباعي", "وضع الحفلة", "الطاقم", "التحالف"]', 0, 400, 20, 8);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What item restores your shield (not health)?', 'أي عنصر يستعيد الدرع (وليس الصحة)؟', NULL, 'text', 'both', NULL, '["Bandages", "Med Kit", "Shield Potion", "Apple"]', '["ضمادات", "عدة إسعاف", "جرعة الدرع", "تفاحة"]', 2, 400, 20, 9);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What''s the max shield you can normally carry?', 'ما أقصى قدر من الدرع يمكن حمله عادة؟', NULL, 'text', 'both', NULL, '["50", "75", "100", "150"]', '["50", "75", "100", "150"]', 2, 400, 20, 10);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What does Fortnite call its big story "seasons" that group together?', 'ماذا تسمي فورتنايت المجموعات الكبيرة من المواسم القصصية؟', NULL, 'text', 'both', NULL, '["Chapters", "Episodes", "Volumes", "Arcs"]', '["فصول", "حلقات", "مجلدات", "أقواس قصصية"]', 0, 600, 20, 11);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'Which of these is NOT a real Fortnite game mode?', 'أي مما يلي ليس نمط لعب حقيقيًا في فورتنايت؟', NULL, 'text', 'both', NULL, '["Zero Build", "Save the World", "Creative", "Farm Frenzy"]', '["Zero Build", "Save the World", "Creative", "Farm Frenzy"]', 3, 600, 20, 12);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What tool do you use to break down structures and gather materials?', 'ما الأداة التي تستخدمها لتفكيك الهياكل وجمع المواد؟', NULL, 'text', 'both', NULL, '["Pickaxe", "Shovel", "Hammer", "Axe"]', '["فأس معول", "مجرفة", "مطرقة", "فأس"]', 0, 600, 20, 13);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'What do players use to jump out of the Battle Bus and float down safely?', 'ماذا يستخدم اللاعبون للقفز من الحافلة القتالية والهبوط بأمان؟', NULL, 'text', 'both', NULL, '["Glider", "Parachute", "Jetpack", "Balloon"]', '["طائرة شراعية", "مظلة", "نفاثة ظهر", "بالون"]', 0, 600, 20, 14);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz3_id, 'Which building material is the strongest?', 'أي مادة بناء هي الأقوى؟', NULL, 'text', 'both', NULL, '["Wood", "Brick", "Metal", "Glass"]', '["خشب", "طوب", "معدن", "زجاج"]', 2, 600, 20, 15);

-- ---------- Quiz: Guess the YouTuber ----------
INSERT INTO quizzes (category_id, title_en, title_ar, description_en, description_ar, cover_image_url, difficulty, supported_modes, created_by_admin_id, is_active)
VALUES (@trivia_royale_cat_id, 'Guess the YouTuber', 'خمّن اليوتيوبر', 'YouTube-red trivia about the biggest creators, streamers and kids'' channels.', 'أسئلة بألوان يوتيوب الحمراء عن أشهر صنّاع المحتوى والستريمرز وقنوات الأطفال.', NULL, 'easy', 'both', NULL, 1);
SET @quiz4_id = LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber is famous for huge stunts and giving away massive prizes?', 'أي يوتيوبر مشهور بالمقالب الضخمة وتوزيع جوائز هائلة؟', NULL, 'text', 'both', NULL, '["MrBeast", "PewDiePie", "Markiplier", "Dream"]', '["MrBeast", "PewDiePie", "Markiplier", "Dream"]', 0, 200, 20, 1);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber built his channel on gaming commentary and was one of the first to hit 100 million subscribers?', 'أي يوتيوبر بنى قناته على التعليق على الألعاب وكان من أوائل من وصلوا إلى 100 مليون مشترك؟', NULL, 'text', 'both', NULL, '["MrBeast", "PewDiePie", "Ninja", "KSI"]', '["MrBeast", "PewDiePie", "Ninja", "KSI"]', 1, 200, 20, 2);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which channel is famous for toy unboxings and became one of the biggest kids'' channels ever?', 'أي قناة اشتهرت بفتح صناديق الألعاب وأصبحت من أكبر قنوات الأطفال على الإطلاق؟', NULL, 'text', 'both', NULL, '["Ryan''s World", "Cocomelon", "Blippi", "SSSniperWolf"]', '["Ryan''s World", "Cocomelon", "Blippi", "SSSniperWolf"]', 0, 200, 20, 3);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which channel features colorful nursery rhymes and is one of the most-viewed kids'' channels ever?', 'أي قناة تعرض أناشيد أطفال ملونة وتُعد من أكثر قنوات الأطفال مشاهدة على الإطلاق؟', NULL, 'text', 'both', NULL, '["Ryan''s World", "Cocomelon", "PJ Masks", "Blippi"]', '["Ryan''s World", "Cocomelon", "PJ Masks", "Blippi"]', 1, 200, 20, 4);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber wears a blue-and-orange outfit and explores places while singing educational songs?', 'أي يوتيوبر يرتدي زيًا أزرق وبرتقاليًا ويستكشف الأماكن مع غناء أغانٍ تعليمية؟', NULL, 'text', 'both', NULL, '["Blippi", "MrBeast", "Dude Perfect", "Markiplier"]', '["Blippi", "MrBeast", "Dude Perfect", "Markiplier"]', 0, 200, 20, 5);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which group of 5 friends is famous for trick-shot and sports comedy videos?', 'أي مجموعة من 5 أصدقاء مشهورة بمقاطع الرميات الخارقة وكوميديا الرياضة؟', NULL, 'text', 'both', NULL, '["Dude Perfect", "Sidemen", "Impaulsive", "2Hype"]', '["Dude Perfect", "Sidemen", "Impaulsive", "2Hype"]', 0, 400, 20, 6);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which British YouTuber group includes members like KSI, Miniminter, and Zerkaa?', 'أي مجموعة يوتيوبرز بريطانية تضم أعضاء مثل KSI وMiniminter وZerkaa؟', NULL, 'text', 'both', NULL, '["Sidemen", "Dream Team", "Vlog Squad", "Merrell Twins"]', '["Sidemen", "Dream Team", "Vlog Squad", "Merrell Twins"]', 0, 400, 20, 7);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber is also a boxer and rapper, with a channel named after his own initials?', 'أي يوتيوبر هو أيضًا ملاكم ومغني راب، وقناته سُميت بأحرف اسمه الأولى؟', NULL, 'text', 'both', NULL, '["KSI", "Logan Paul", "PewDiePie", "James Charles"]', '["KSI", "Logan Paul", "PewDiePie", "James Charles"]', 0, 400, 20, 8);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber is famous for Minecraft "Manhunt" videos where people try to catch him in-game?', 'أي يوتيوبر اشتهر بمقاطع "Manhunt" في ماينكرافت حيث يحاول آخرون الإمساك به داخل اللعبة؟', NULL, 'text', 'both', NULL, '["Dream", "Technoblade", "MrBeast", "TommyInnit"]', '["Dream", "Technoblade", "MrBeast", "TommyInnit"]', 0, 400, 20, 9);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'What''s the general term for people who follow a YouTuber''s channel?', 'ما المصطلح العام للأشخاص الذين يتابعون قناة يوتيوبر؟', NULL, 'text', 'both', NULL, '["Subscribers", "Followers", "Fans", "Viewers"]', '["مشتركون", "متابعون", "معجبون", "مشاهدون"]', 0, 400, 20, 10);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber is known for makeup and beauty tutorials, one of the first big beauty gurus?', 'أي يوتيوبر معروف بدروس المكياج والجمال، وكان من أوائل خبراء الجمال الكبار؟', NULL, 'text', 'both', NULL, '["James Charles", "MrBeast", "Markiplier", "Ninja"]', '["James Charles", "MrBeast", "Markiplier", "Ninja"]', 0, 600, 20, 11);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'What''s the button called that viewers click to follow a YouTuber''s channel updates?', 'ما اسم الزر الذي يضغطه المشاهدون لمتابعة تحديثات قناة يوتيوبر؟', NULL, 'text', 'both', NULL, '["Like button", "Subscribe button", "Bell icon", "Share button"]', '["زر الإعجاب", "زر الاشتراك", "أيقونة الجرس", "زر المشاركة"]', 1, 600, 20, 12);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which streamer helped make Fortnite huge and once had one of the most-watched gaming streams ever, featuring Drake?', 'أي ستريمر ساهم في جعل فورتنايت مشهورة جدًا وكان له أحد أكثر بثوث الألعاب مشاهدة على الإطلاق مع دريك؟', NULL, 'text', 'both', NULL, '["Ninja", "Dream", "MrBeast", "Markiplier"]', '["Ninja", "Dream", "MrBeast", "Markiplier"]', 0, 600, 20, 13);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'What''s it called when a YouTuber posts a video responding to someone else''s content?', 'ماذا يُسمى عندما ينشر يوتيوبر مقطعًا يرد فيه على محتوى شخص آخر؟', NULL, 'text', 'both', NULL, '["Repost", "Reaction video", "Remix", "Rewind"]', '["إعادة نشر", "فيديو رد فعل", "ريمكس", "Rewind"]', 1, 600, 20, 14);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz4_id, 'Which YouTuber is known for the catchphrase "Top of the mornin'' to ya" and a red mustache logo?', 'أي يوتيوبر معروف بعبارته المميزة "Top of the mornin'' to ya" وشعار الشارب الأحمر؟', NULL, 'text', 'both', NULL, '["PewDiePie", "Jacksepticeye", "Markiplier", "Ninja"]', '["PewDiePie", "Jacksepticeye", "Markiplier", "Ninja"]', 1, 600, 20, 15);

-- ---------- Quiz: Guess the Snack ----------
INSERT INTO quizzes (category_id, title_en, title_ar, description_en, description_ar, cover_image_url, difficulty, supported_modes, created_by_admin_id, is_active)
VALUES (@trivia_royale_cat_id, 'Guess the Snack', 'خمّن الوجبة الخفيفة', 'Orange and yellow candy-wrapper trivia about the world''s favorite snacks and chips.', 'أسئلة بألوان برتقالية وصفراء عن أشهر الوجبات الخفيفة والحلويات في العالم.', NULL, 'easy', 'both', NULL, 1);
SET @quiz5_id = LAST_INSERT_ID();

INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'What snack turns your fingers orange and is famously "cheesy"?', 'أي وجبة خفيفة تلوّن أصابعك باللون البرتقالي وتشتهر بنكهتها الجبنية؟', NULL, 'text', 'both', NULL, '["Doritos", "Cheetos", "Pringles", "Cheez-Its"]', '["Doritos", "Cheetos", "Pringles", "Cheez-Its"]', 1, 200, 20, 1);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'What shape are original Pringles chips?', 'ما شكل رقائق برينجلز الأصلية؟', NULL, 'text', 'both', NULL, '["Round and flat", "Curved saddle shape", "Triangle", "Square"]', '["دائري ومسطح", "شكل سرج منحني", "مثلث", "مربع"]', 1, 200, 20, 2);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which candy''s slogan is "Melts in your mouth, not in your hand"?', 'أي حلوى شعارها "تذوب في فمك، لا في يدك"؟', NULL, 'text', 'both', NULL, '["Skittles", "M&M''s", "Reese''s", "Starburst"]', '["Skittles", "M&M''s", "Reese''s", "Starburst"]', 1, 200, 20, 3);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'What''s Skittles'' famous slogan?', 'ما شعار Skittles الشهير؟', NULL, 'text', 'both', NULL, '["Taste the Rainbow", "Melts in your mouth", "Snap Crackle Pop", "I''m Lovin'' It"]', '["Taste the Rainbow", "Melts in your mouth", "Snap Crackle Pop", "I''m Lovin'' It"]', 0, 200, 20, 4);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which snack is a stack of crunchy chips you eat "once you pop"?', 'أي وجبة خفيفة عبارة عن كومة من الرقائق المقرمشة التي بمجرد أن تبدأ لا يمكنك التوقف؟', NULL, 'text', 'both', NULL, '["Pringles", "Lays", "Doritos", "Ruffles"]', '["Pringles", "Lays", "Doritos", "Ruffles"]', 0, 200, 20, 5);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which cookie has a creamy filling between two chocolate wafers, often twisted apart before eating?', 'أي بسكويت يحتوي على حشوة كريمية بين طبقتين من الويفر بالشوكولاتة، ويُفصل غالبًا قبل الأكل؟', NULL, 'text', 'both', NULL, '["Chips Ahoy", "Oreo", "Nutter Butter", "Milano"]', '["Chips Ahoy", "Oreo", "Nutter Butter", "Milano"]', 1, 400, 20, 6);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'What''s the mascot of Cheetos?', 'ما هي شخصية تشيتوس الرمزية؟', NULL, 'text', 'both', NULL, '["Chester Cheetah", "Tony the Tiger", "Cap''n Crunch", "Snap the Elf"]', '["Chester Cheetah", "Tony the Tiger", "Cap''n Crunch", "Snap the Elf"]', 0, 400, 20, 7);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which chocolate bar is shaped like triangular chunks meant to look like mountains?', 'أي لوح شوكولاتة على شكل قطع مثلثية تشبه الجبال؟', NULL, 'text', 'both', NULL, '["Twix", "Toblerone", "KitKat", "Snickers"]', '["Twix", "Toblerone", "KitKat", "Snickers"]', 1, 400, 20, 8);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which candy bar''s jingle is "Give me a break," referring to its snap-able bars?', 'أي لوح حلوى شعاره الغنائي "Give me a break" في إشارة إلى أصابعه القابلة للكسر؟', NULL, 'text', 'both', NULL, '["Twix", "KitKat", "Snickers", "Milky Way"]', '["Twix", "KitKat", "Snickers", "Milky Way"]', 1, 400, 20, 9);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which snack''s slogan is "You''re not you when you''re hungry"?', 'أي وجبة خفيفة شعارها "لست نفسك عندما تجوع"؟', NULL, 'text', 'both', NULL, '["Snickers", "Twix", "Milky Way", "Butterfinger"]', '["Snickers", "Twix", "Milky Way", "Butterfinger"]', 0, 400, 20, 10);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which candy is famously called "the two-finger candy bar"?', 'أي حلوى تُعرف باسم "لوح الإصبعين"؟', NULL, 'text', 'both', NULL, '["KitKat", "Twix", "Milky Way", "3 Musketeers"]', '["KitKat", "Twix", "Milky Way", "3 Musketeers"]', 1, 600, 20, 11);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'What popular snack food is made from popped corn and eaten at movies?', 'ما الوجبة الخفيفة الشهيرة المصنوعة من الذرة المتفجرة وتُؤكل في السينما؟', NULL, 'text', 'both', NULL, '["Popcorn", "Pretzels", "Chips", "Cotton candy"]', '["فشار", "بريتزل", "رقائق", "غزل البنات"]', 0, 600, 20, 12);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which brand makes the little smiling, goldfish-shaped cheese crackers?', 'أي علامة تجارية تصنع مقرمشات الجبن الصغيرة على شكل سمك ذهبي مبتسم؟', NULL, 'text', 'both', NULL, '["Cheez-It", "Goldfish", "Ritz", "Wheat Thins"]', '["Cheez-It", "Goldfish", "Ritz", "Wheat Thins"]', 1, 600, 20, 13);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which extremely sour candy''s wrapper features a skull logo?', 'أي حلوى شديدة الحموضة يحمل غلافها شعار جمجمة؟', NULL, 'text', 'both', NULL, '["Warheads", "Sour Patch Kids", "Nerds", "Skittles"]', '["Warheads", "Sour Patch Kids", "Nerds", "Skittles"]', 0, 600, 20, 14);
INSERT INTO quiz_questions (quiz_id, question_text_en, question_text_ar, question_image_url, question_type, mode, media_url, options_json_en, options_json_ar, correct_option_index, points, time_limit_seconds, sort_order)
VALUES (@quiz5_id, 'Which chip brand is famous for its "Flamin'' Hot" flavor with red spicy dust?', 'أي علامة رقائق مشهورة بنكهة "Flamin'' Hot" ذات المسحوق الأحمر الحار؟', NULL, 'text', 'both', NULL, '["Flamin'' Hot Cheetos", "Flamin'' Hot Doritos", "Flamin'' Hot Pringles", "Flamin'' Hot Fritos"]', '["Flamin'' Hot Cheetos", "Flamin'' Hot Doritos", "Flamin'' Hot Pringles", "Flamin'' Hot Fritos"]', 0, 600, 20, 15);

COMMIT;

-- Rows inserted: 1 category, 5 quizzes, 66 questions.
-- NOTE: 'Makedown History' is inserted with is_active = 0 and only 6 of 15
-- questions (the ones with real answers). Questions 7-15 need real facts
-- about Makedown before they can be added - see chat for the list.
-- Once those are added, set quizzes.is_active = 1 for that quiz.
